backend:
  name: git-gateway
  branch: master
  repo: alexanderson1993/portfolio.nataliebrianne.com

media_folder: "public/assets"
public_folder: "/public/assets"

# Picture Page
# - Title
# - Description
# - Medium

# Testimonial
# - Testimonial
# - Name
collections: # A list of collections the CMS should be able to edit
  - name: "items"
    label: "Portfolio Items"
    label_singular: "Portfolio Item"
    folder: "content/portfolio"
    slug: "{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Full Width", name: "full", widget: "boolean", default: false }
      - { label: "Medium", name: "medium", widget: "string", tagname: "small" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: "testimonials"
    label: "Testimonials"
    label_singular: "testimonial"
    folder: "content/testimonials"
    slug: "{{slug}}"
    create: true
    delete: true
    fields:
      - { label: "Name", name: "name", widget: "string", tagname: "p" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Hire Me"
        name: "hireme"
        file: "content/hireme.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
